### ISSUE TITLE
In Game_Enemy.prototype.findAction, why are action ratings multiplied by 3?

### ISSUE THREAD

**Issue by jwrush** [emb-12/Tactics-System#2]
This happens when the sum of action ratings for a tile is being calculated.

Why are all the ratings multiplied by 3?  It seems like this just makes the numbers higher.

**Comment by belmoussaoui** [comment]
just because i'm a buffoon! haha! also because i had fun with an "ia manager" who wasn't released/complete and i needed numbers higher. i'll fix that. thanks
